sudo: false
cache: pip
language: python
python:
- '2.7'
- '3.6'

install:
    - pip install sphinx travis-sphinx

script:
    - travis-sphinx build
    
after_success:
    - travis-sphinx deploy
    
branches:
  only:
    - master
