exclude_zeros: False
recompute_all_derivatives: False

functional_start_index: 0
functional_stop_index: End

output_directory: /tmp/output
working_directory: /tmp/workdir
log_directory: /tmp/output/logs

s3_read_credentials: 
s3_write_credentials: 

bundle_size: 1
num_processors: 1
available_memory: 4

save_working_dir: False
write_graph: False
write_report: False