'01':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-01/anat/sub-01_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-01/func/sub-01_task-rhymejudgment_bold.nii.gz}
'02':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-02/anat/sub-02_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-02/func/sub-02_task-rhymejudgment_bold.nii.gz}
'03':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-03/anat/sub-03_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-03/func/sub-03_task-rhymejudgment_bold.nii.gz}
'04':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-04/anat/sub-04_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-04/func/sub-04_task-rhymejudgment_bold.nii.gz}
'05':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-05/anat/sub-05_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-05/func/sub-05_task-rhymejudgment_bold.nii.gz}
'06':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-06/anat/sub-06_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-06/func/sub-06_task-rhymejudgment_bold.nii.gz}
'07':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-07/anat/sub-07_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-07/func/sub-07_task-rhymejudgment_bold.nii.gz}
08:
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-08/anat/sub-08_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-08/func/sub-08_task-rhymejudgment_bold.nii.gz}
09:
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-09/anat/sub-09_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-09/func/sub-09_task-rhymejudgment_bold.nii.gz}
'10':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-10/anat/sub-10_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-10/func/sub-10_task-rhymejudgment_bold.nii.gz}
'11':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-11/anat/sub-11_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-11/func/sub-11_task-rhymejudgment_bold.nii.gz}
'12':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-12/anat/sub-12_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-12/func/sub-12_task-rhymejudgment_bold.nii.gz}
'13':
  session_1:
    anatomical_scan: {anat_1: /Users/filo/data/ds003_downsampled/sub-13/anat/sub-13_T1w.nii.gz}
    functional_scan: {func_1: /Users/filo/data/ds003_downsampled/sub-13/func/sub-13_task-rhymejudgment_bold.nii.gz}
