num_cores_per_subject: 1

num_subjects_at_once: 1

output_directory: /mnt/output

working_directory: /mnt/working

write_all_outputs: False

template_brain_for_anat: /opt/afni/bin/MNI_avg152T1+tlrc.HEAD

template_skull_for_anat: /opt/afni/bin/MNI_avg152T1+tlrc.HEAD

write_report: False

write_graph: True
