num_cores_per_subject: 4

num_subjects_at_once: 1

num_ants_threads: 4
 
output_directory: /mnt/output

working_directory: /mnt/working

template_brain_for_anat: /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm_brain.nii.gz

template_skull_for_anat: /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm.nii.gz
