num_cores_per_subject: 4

num_subjects_at_once: 1

num_ants_threads: 4
 
output_directory: /mnt/output

working_directory: /mnt/working

template_brain_for_anat: /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm_brain.nii.gz

template_skull_for_anat: /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm.nii.gz

csf_threshold: 0.98

gm_threshold: 0.7

wm_threshold: 0.98

prior_csf: /usr/share/fsl/5.0/data/standard/tissuepriors/2mm/avg152T1_csf_bin.nii.gz

prior_gm: /usr/share/fsl/5.0/data/standard/tissuepriors/2mm/avg152T1_gray_bin.nii.gz

prior_wm: /usr/share/fsl/5.0/data/standard/tissuepriors/2mm/avg152T1_white_bin.nii.gz
