num_cores_per_subject: 1

num_subjects_at_once: 1

output_directory: /tmp/output

working_directory: /tmp/workdir

write_all_outputs: False

template_brain_for_anat: ~/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz

template_skull_for_anat: ~/fsl/data/standard/MNI152_T1_2mm.nii.gz

start_idx: 0

stop_idx: None

slice_timing_correction: False
